# Site settings
email:zhenyuan_hao@163.com
baseurl: "haohhxx.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: haohhxx
description: 学习笔记
url: "haohhxx.github.io"
twitter_username:
default_img:

# Profile settings
name:
profile_img:
profile:
social:
  github:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
